import "./MyArt.css"

const MyArt = () =>{
    return(
        <div className="MyArt">
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure molestiae deserunt modi tempore voluptatem vel amet! Explicabo unde amet ea, optio impedit sapiente sunt ipsum tenetur doloremque earum eveniet nobis assumenda magni vero nostrum animi, harum vitae, incidunt necessitatibus beatae voluptate quam modi praesentium facere? Aspernatur hic autem accusamus deserunt pariatur optio, obcaecati deleniti velit quasi perspiciatis neque nihil rerum. Libero tenetur laboriosam quo voluptate maiores illum tempore quidem consequatur dolores error. Provident inventore reprehenderit ducimus nemo dolore eaque tenetur, voluptatibus vel placeat eum sit magni assumenda deleniti facere, eveniet suscipit velit? Repudiandae recusandae cupiditate mollitia minus quas consequatur maiores, soluta fuga alias modi! Reprehenderit commodi officiis odio provident iste, porro, quos accusamus saepe debitis non illum neque quod. Quae laboriosam, cumque maiores odit dolorem sed voluptas perferendis ducimus veniam, commodi molestias quidem distinctio incidunt sit cum vero non a illum, vitae fugit tempore? Sed sapiente eveniet dicta nulla, ipsa laudantium? Numquam, vitae expedita doloremque optio quidem nemo ullam impedit aperiam fuga at illum totam aspernatur, ducimus velit perferendis repellat? Sint ratione voluptas ipsa iste alias tempora impedit ea architecto in vitae quidem dolor, consequatur dolore! Minima aspernatur alias accusamus, repudiandae atque unde id nisi deleniti adipisci nesciunt corporis incidunt labore reiciendis. Ducimus soluta fugiat minus ipsam, ut minima molestiae vel eum fuga ullam ratione corrupti omnis optio temporibus voluptas quam magni voluptate corporis ea? Vitae, eveniet ea rerum nulla, eaque temporibus consequatur odit modi omnis nobis expedita voluptatum provident? Rerum eos quidem ducimus qui debitis repellat incidunt tempore alias nam eius, nobis tenetur quam nemo, excepturi facere facilis dolorum modi porro illum. Accusantium iste error fuga quam fugiat! Laborum facere impedit eum et. Quos repudiandae eveniet odit cum qui, quis nobis exercitationem obcaecati numquam, error consectetur, ratione sint cumque officia quod iusto ducimus ab est nisi vitae pariatur id. Facilis sequi numquam quo modi hic est perferendis. Temporibus velit consectetur necessitatibus rem. Tenetur, perspiciatis a! Nostrum distinctio nam saepe numquam perspiciatis reiciendis consequatur illo deleniti, veritatis sint magnam eos illum provident adipisci deserunt dolores delectus officia fuga rerum architecto voluptas obcaecati dicta! Ea.</p>
        </div>
    )
}

export default MyArt